apiVersion: config.pkg.pkgserver.dev/v1alpha1
kind: PackageVariant
metadata:
  name: pv-kform-test
  namespace: default
spec:
  upstream:
    repository: repo-catalog
    realm: nf
    package: example
    revision: v3
  downstream:
    target: dummy
    repository: repo-target
    realm: nf
    package: example
  packageContext:
    readinessGates:
    - conditionType: pkg.pkgserver.dev/process
    labels:
      a: b
    annotations:
      policy.pkg.kform.dev/approval: initial
