/*
Copyright 2024 Nokia.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ // Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/pkgserver-dev/pkgserver/apis/pkg/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	condition "github.com/pkgserver-dev/pkgserver/apis/condition"
	pkgid "github.com/pkgserver-dev/pkgserver/apis/pkgid"
	v11 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *PackageRevision) Reset()      { *m = PackageRevision{} }
func (*PackageRevision) ProtoMessage() {}
func (*PackageRevision) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{0}
}
func (m *PackageRevision) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevision.Merge(m, src)
}
func (m *PackageRevision) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevision) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevision.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevision proto.InternalMessageInfo

func (m *PackageRevisionApproval) Reset()      { *m = PackageRevisionApproval{} }
func (*PackageRevisionApproval) ProtoMessage() {}
func (*PackageRevisionApproval) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{1}
}
func (m *PackageRevisionApproval) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionApproval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionApproval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionApproval.Merge(m, src)
}
func (m *PackageRevisionApproval) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionApproval) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionApproval.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionApproval proto.InternalMessageInfo

func (m *PackageRevisionDependencies) Reset()      { *m = PackageRevisionDependencies{} }
func (*PackageRevisionDependencies) ProtoMessage() {}
func (*PackageRevisionDependencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{2}
}
func (m *PackageRevisionDependencies) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionDependencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionDependencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionDependencies.Merge(m, src)
}
func (m *PackageRevisionDependencies) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionDependencies) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionDependencies.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionDependencies proto.InternalMessageInfo

func (m *PackageRevisionDependency) Reset()      { *m = PackageRevisionDependency{} }
func (*PackageRevisionDependency) ProtoMessage() {}
func (*PackageRevisionDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{3}
}
func (m *PackageRevisionDependency) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionDependency.Merge(m, src)
}
func (m *PackageRevisionDependency) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionDependency.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionDependency proto.InternalMessageInfo

func (m *PackageRevisionDependencyError) Reset()      { *m = PackageRevisionDependencyError{} }
func (*PackageRevisionDependencyError) ProtoMessage() {}
func (*PackageRevisionDependencyError) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{4}
}
func (m *PackageRevisionDependencyError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionDependencyError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionDependencyError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionDependencyError.Merge(m, src)
}
func (m *PackageRevisionDependencyError) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionDependencyError) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionDependencyError.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionDependencyError proto.InternalMessageInfo

func (m *PackageRevisionList) Reset()      { *m = PackageRevisionList{} }
func (*PackageRevisionList) ProtoMessage() {}
func (*PackageRevisionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{5}
}
func (m *PackageRevisionList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionList.Merge(m, src)
}
func (m *PackageRevisionList) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionList) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionList.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionList proto.InternalMessageInfo

func (m *PackageRevisionResources) Reset()      { *m = PackageRevisionResources{} }
func (*PackageRevisionResources) ProtoMessage() {}
func (*PackageRevisionResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{6}
}
func (m *PackageRevisionResources) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionResources.Merge(m, src)
}
func (m *PackageRevisionResources) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionResources) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionResources.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionResources proto.InternalMessageInfo

func (m *PackageRevisionResourcesList) Reset()      { *m = PackageRevisionResourcesList{} }
func (*PackageRevisionResourcesList) ProtoMessage() {}
func (*PackageRevisionResourcesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{7}
}
func (m *PackageRevisionResourcesList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionResourcesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionResourcesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionResourcesList.Merge(m, src)
}
func (m *PackageRevisionResourcesList) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionResourcesList) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionResourcesList.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionResourcesList proto.InternalMessageInfo

func (m *PackageRevisionResourcesSpec) Reset()      { *m = PackageRevisionResourcesSpec{} }
func (*PackageRevisionResourcesSpec) ProtoMessage() {}
func (*PackageRevisionResourcesSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{8}
}
func (m *PackageRevisionResourcesSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionResourcesSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionResourcesSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionResourcesSpec.Merge(m, src)
}
func (m *PackageRevisionResourcesSpec) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionResourcesSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionResourcesSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionResourcesSpec proto.InternalMessageInfo

func (m *PackageRevisionResourcesStatus) Reset()      { *m = PackageRevisionResourcesStatus{} }
func (*PackageRevisionResourcesStatus) ProtoMessage() {}
func (*PackageRevisionResourcesStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{9}
}
func (m *PackageRevisionResourcesStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionResourcesStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionResourcesStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionResourcesStatus.Merge(m, src)
}
func (m *PackageRevisionResourcesStatus) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionResourcesStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionResourcesStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionResourcesStatus proto.InternalMessageInfo

func (m *PackageRevisionSpec) Reset()      { *m = PackageRevisionSpec{} }
func (*PackageRevisionSpec) ProtoMessage() {}
func (*PackageRevisionSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{10}
}
func (m *PackageRevisionSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionSpec.Merge(m, src)
}
func (m *PackageRevisionSpec) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionSpec proto.InternalMessageInfo

func (m *PackageRevisionStatus) Reset()      { *m = PackageRevisionStatus{} }
func (*PackageRevisionStatus) ProtoMessage() {}
func (*PackageRevisionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{11}
}
func (m *PackageRevisionStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackageRevisionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PackageRevisionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRevisionStatus.Merge(m, src)
}
func (m *PackageRevisionStatus) XXX_Size() int {
	return m.Size()
}
func (m *PackageRevisionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRevisionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRevisionStatus proto.InternalMessageInfo

func (m *Task) Reset()      { *m = Task{} }
func (*Task) ProtoMessage() {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_de78af8f6fb6d32f, []int{12}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return m.Size()
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PackageRevision)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevision")
	proto.RegisterType((*PackageRevisionApproval)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionApproval")
	proto.RegisterType((*PackageRevisionDependencies)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionDependencies")
	proto.RegisterType((*PackageRevisionDependency)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionDependency")
	proto.RegisterType((*PackageRevisionDependencyError)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionDependencyError")
	proto.RegisterType((*PackageRevisionList)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionList")
	proto.RegisterType((*PackageRevisionResources)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionResources")
	proto.RegisterType((*PackageRevisionResourcesList)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionResourcesList")
	proto.RegisterType((*PackageRevisionResourcesSpec)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionResourcesSpec")
	proto.RegisterMapType((map[string]string)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionResourcesSpec.ResourcesEntry")
	proto.RegisterType((*PackageRevisionResourcesStatus)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionResourcesStatus")
	proto.RegisterType((*PackageRevisionSpec)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionSpec")
	proto.RegisterType((*PackageRevisionStatus)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.PackageRevisionStatus")
	proto.RegisterType((*Task)(nil), "github.com.pkgserver_dev.pkgserver.apis.pkg.v1alpha1.Task")
}

func init() {
	proto.RegisterFile("github.com/pkgserver-dev/pkgserver/apis/pkg/v1alpha1/generated.proto", fileDescriptor_de78af8f6fb6d32f)
}

var fileDescriptor_de78af8f6fb6d32f = []byte{
	// 1212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xda, 0xb1, 0x6b, 0x4f, 0x4c, 0x48, 0x27, 0x40, 0xb7, 0x01, 0xec, 0xca, 0x20, 0x54,
	0x21, 0xb2, 0x26, 0x55, 0x80, 0xa8, 0x02, 0x44, 0x96, 0x44, 0x10, 0xb5, 0xd0, 0x30, 0x24, 0x42,
	0xaa, 0x90, 0xca, 0x64, 0xf7, 0xc5, 0x99, 0xda, 0xde, 0x5d, 0xed, 0x8c, 0xdd, 0x5a, 0x42, 0xa8,
	0x42, 0x42, 0x70, 0x41, 0x42, 0xf0, 0x45, 0xb8, 0x70, 0xe7, 0x98, 0x63, 0x2f, 0x95, 0x7a, 0x40,
	0x86, 0x98, 0x2f, 0x00, 0xd7, 0x9c, 0xd0, 0xce, 0x8e, 0x77, 0xed, 0xdd, 0xb8, 0x4d, 0x2c, 0xb7,
	0xe2, 0xe6, 0x37, 0x33, 0xef, 0xf7, 0x7b, 0xef, 0xcd, 0xfb, 0x33, 0x6b, 0xb4, 0x51, 0x67, 0xe2,
	0xa0, 0xbd, 0x67, 0x58, 0x6e, 0xab, 0xe6, 0x35, 0xea, 0x1c, 0xfc, 0x0e, 0xf8, 0xcb, 0x36, 0x74,
	0x62, 0xa9, 0x46, 0x3d, 0xc6, 0x03, 0xb1, 0xd6, 0x59, 0xa1, 0x4d, 0xef, 0x80, 0xae, 0xd4, 0xea,
	0xe0, 0x80, 0x4f, 0x05, 0xd8, 0x86, 0xe7, 0xbb, 0xc2, 0xc5, 0xab, 0x31, 0x8a, 0x11, 0xe9, 0xdd,
	0xb2, 0xa1, 0x13, 0x4b, 0x46, 0x80, 0x12, 0x88, 0xc6, 0x00, 0x65, 0x69, 0x79, 0x88, 0xbb, 0xee,
	0xd6, 0xdd, 0x9a, 0x04, 0xdb, 0x6b, 0xef, 0x4b, 0x49, 0x0a, 0xf2, 0x57, 0x48, 0xb2, 0xb4, 0x7e,
	0x5a, 0x53, 0x2d, 0xd7, 0xb1, 0x99, 0x60, 0xae, 0x93, 0xb4, 0x73, 0xe9, 0xbd, 0x33, 0x78, 0xcb,
	0xec, 0x94, 0x7a, 0xb5, 0xb1, 0xc6, 0x0d, 0xe6, 0x06, 0x47, 0x6a, 0x96, 0xeb, 0x43, 0xad, 0x93,
	0x0a, 0xc5, 0xd2, 0x6a, 0x7c, 0xa6, 0x45, 0xad, 0x03, 0xe6, 0x80, 0xdf, 0x95, 0xc1, 0x93, 0xb8,
	0x2d, 0x10, 0xf4, 0x24, 0xad, 0xda, 0x38, 0x2d, 0xbf, 0xed, 0x08, 0xd6, 0x82, 0x94, 0xc2, 0xdb,
	0x8f, 0x53, 0xe0, 0xd6, 0x01, 0xb4, 0x68, 0x52, 0xaf, 0xfa, 0x20, 0x83, 0x9e, 0xdd, 0xa6, 0x56,
	0x83, 0xd6, 0x81, 0x40, 0x87, 0x71, 0xe6, 0x3a, 0xf8, 0x2b, 0x54, 0x08, 0xec, 0xb2, 0xa9, 0xa0,
	0xba, 0x76, 0x49, 0xbb, 0x3c, 0x77, 0xe5, 0x4d, 0x23, 0x84, 0x37, 0x86, 0xe1, 0xe5, 0xe5, 0xc9,
	0x5b, 0x0c, 0x4e, 0x1b, 0x9d, 0x15, 0xe3, 0xc6, 0xde, 0x6d, 0xb0, 0xc4, 0x27, 0x20, 0xa8, 0x89,
	0x0f, 0x7b, 0x95, 0x99, 0x7e, 0xaf, 0x82, 0xe2, 0x35, 0x12, 0xa1, 0xe2, 0x06, 0x9a, 0xe5, 0x1e,
	0x58, 0x7a, 0x46, 0xa2, 0x6f, 0x19, 0x93, 0xa4, 0x8b, 0x91, 0x30, 0xfb, 0x73, 0x0f, 0x2c, 0xb3,
	0xa4, 0x68, 0x67, 0x03, 0x89, 0x48, 0x12, 0xcc, 0x51, 0x9e, 0x0b, 0x2a, 0xda, 0x5c, 0xcf, 0x4a,
	0xba, 0x6b, 0xd3, 0xa1, 0x93, 0x90, 0xe6, 0xbc, 0x22, 0xcc, 0x87, 0x32, 0x51, 0x54, 0xd5, 0x8b,
	0xe8, 0x42, 0x42, 0x61, 0xdd, 0xf3, 0x7c, 0xb7, 0x43, 0x9b, 0xd5, 0xdf, 0xb3, 0xe8, 0xc5, 0xc4,
	0xde, 0x06, 0x78, 0xe0, 0xd8, 0xe0, 0x58, 0x0c, 0x38, 0xae, 0xa0, 0x1c, 0xf8, 0xbe, 0xeb, 0xcb,
	0xd8, 0x17, 0xcd, 0x62, 0xbf, 0x57, 0xc9, 0x6d, 0x06, 0x0b, 0x24, 0x5c, 0xc7, 0x77, 0x51, 0x5e,
	0xfe, 0xe0, 0x7a, 0xe6, 0x52, 0xf6, 0xf2, 0xdc, 0x95, 0x9d, 0xa9, 0x38, 0x14, 0xd9, 0xd0, 0x95,
	0x64, 0x26, 0x0a, 0xbc, 0x92, 0x3f, 0x39, 0x51, 0x7c, 0xf8, 0x1b, 0x54, 0xb8, 0x43, 0x7d, 0x87,
	0x39, 0xf5, 0x20, 0x98, 0x4f, 0x8e, 0xbb, 0xd4, 0xef, 0x55, 0x0a, 0x5f, 0x28, 0x26, 0x12, 0x71,
	0xe2, 0xef, 0x34, 0x54, 0xb2, 0x87, 0x62, 0xa5, 0xcf, 0x4a, 0x23, 0x6e, 0x4c, 0xd9, 0x08, 0x73,
	0xa1, 0xdf, 0xab, 0x94, 0x86, 0x2f, 0x85, 0x8c, 0xd0, 0x56, 0x7f, 0xc9, 0xa2, 0x8b, 0x63, 0xb5,
	0xf1, 0x3a, 0x9a, 0x15, 0x5d, 0x0f, 0xd4, 0xfd, 0x2d, 0x0f, 0x52, 0x72, 0xa7, 0xeb, 0xc1, 0x71,
	0xaf, 0xf2, 0xf2, 0x58, 0xc5, 0xe0, 0x00, 0x91, 0xaa, 0xf8, 0x7d, 0x94, 0xf5, 0x61, 0x5f, 0xd5,
	0xc7, 0x2b, 0x43, 0xd5, 0x67, 0x04, 0x7d, 0x26, 0xae, 0x35, 0x02, 0xfb, 0xe0, 0x83, 0x63, 0x81,
	0x79, 0xae, 0xdf, 0xab, 0x64, 0x09, 0xec, 0x93, 0x40, 0x11, 0x7f, 0xab, 0xa1, 0x45, 0x2f, 0xe4,
	0x19, 0x76, 0x43, 0x5d, 0xda, 0x3b, 0x67, 0x89, 0x17, 0xb3, 0x8d, 0x5d, 0x8f, 0x0b, 0x1f, 0x68,
	0xcb, 0xbc, 0xd0, 0xef, 0x55, 0x16, 0xb7, 0xd3, 0xb8, 0xe4, 0x24, 0x32, 0xec, 0xa0, 0x45, 0xd5,
	0x7d, 0x36, 0xd2, 0x77, 0x76, 0x2a, 0xa7, 0x24, 0x1f, 0x49, 0x63, 0x90, 0x93, 0x80, 0xab, 0x3f,
	0x68, 0xa8, 0xfc, 0xe8, 0xc4, 0x1a, 0xc4, 0x55, 0x9b, 0x34, 0xae, 0xaf, 0xa1, 0xbc, 0x0f, 0x94,
	0xbb, 0x8e, 0xbc, 0x9a, 0x62, 0x5c, 0xfe, 0x44, 0xae, 0x12, 0xb5, 0x5b, 0xfd, 0x53, 0x43, 0x8b,
	0x09, 0x53, 0xae, 0x33, 0x2e, 0xf0, 0x97, 0xa9, 0xd6, 0x6a, 0x9c, 0xae, 0xb5, 0x06, 0xda, 0xb2,
	0xb1, 0x2e, 0x28, 0xc6, 0xc2, 0x60, 0x65, 0xa8, 0xad, 0xde, 0x46, 0x39, 0x26, 0xa0, 0x35, 0xe8,
	0x0b, 0x9b, 0x53, 0x29, 0x0b, 0xf3, 0x19, 0xc5, 0x98, 0xdb, 0x0a, 0xb0, 0x49, 0x48, 0x51, 0xfd,
	0x27, 0x83, 0xf4, 0xc4, 0x49, 0x02, 0xdc, 0x6d, 0xfb, 0x16, 0xf0, 0xa7, 0x30, 0x41, 0xc4, 0xc8,
	0x04, 0x21, 0x53, 0xf1, 0x34, 0xb2, 0x7f, 0xec, 0x28, 0xf9, 0x3a, 0x31, 0x4a, 0x76, 0xa6, 0xcc,
	0xfb, 0xe8, 0x99, 0xf2, 0xaf, 0x86, 0x5e, 0x1a, 0xa7, 0xfa, 0x14, 0xb2, 0x8b, 0x8f, 0x66, 0xd7,
	0xa7, 0xd3, 0xf5, 0x7d, 0x4c, 0x9a, 0xfd, 0x91, 0x19, 0xef, 0x73, 0x70, 0x31, 0x98, 0xa1, 0xa2,
	0xea, 0x3d, 0x5b, 0x1b, 0x7a, 0x5e, 0x3a, 0xbd, 0x76, 0xc6, 0xf6, 0xb6, 0x3d, 0xd0, 0x37, 0xcf,
	0x2b, 0x1b, 0x8a, 0xd1, 0x12, 0x89, 0xd1, 0xf1, 0xcf, 0x1a, 0x2a, 0xfa, 0x03, 0x72, 0x5d, 0x93,
	0x51, 0xa0, 0xd3, 0xcf, 0x3c, 0x23, 0x92, 0x36, 0x1d, 0xe1, 0x77, 0x63, 0xa3, 0xa2, 0x75, 0x12,
	0x9b, 0xb1, 0xf4, 0x2e, 0x9a, 0x1f, 0x3d, 0x8f, 0x17, 0x50, 0xb6, 0x01, 0xdd, 0x70, 0xfa, 0x90,
	0xe0, 0x27, 0x7e, 0x0e, 0xe5, 0x3a, 0xb4, 0xd9, 0x86, 0xb0, 0x69, 0x91, 0x50, 0xb8, 0x9a, 0x59,
	0xd3, 0xaa, 0xbf, 0xa6, 0x5b, 0x66, 0x22, 0x1b, 0xf1, 0x8f, 0x1a, 0x3a, 0x1f, 0xbd, 0xa0, 0xc1,
	0x0e, 0x57, 0x55, 0x7a, 0x6d, 0x9c, 0xda, 0xfb, 0x08, 0xc1, 0xf8, 0x30, 0x89, 0x65, 0x5e, 0x54,
	0x0e, 0x9e, 0x4f, 0x6d, 0x91, 0x34, 0x73, 0xf5, 0xb7, 0x5c, 0xaa, 0xb5, 0xa6, 0x13, 0x41, 0x7b,
	0xa2, 0x89, 0x70, 0x0d, 0x15, 0x9b, 0x6c, 0x1f, 0xac, 0xae, 0xd5, 0x54, 0x31, 0x8d, 0xa6, 0x7c,
	0xf1, 0xfa, 0x60, 0xe3, 0xb8, 0x57, 0xd1, 0x53, 0x23, 0x40, 0xed, 0x91, 0x58, 0x1f, 0x7f, 0x8c,
	0x4a, 0x6d, 0xcf, 0xa6, 0x02, 0xb6, 0xdd, 0x26, 0xb3, 0xba, 0xb2, 0xb3, 0x14, 0xcd, 0x57, 0x15,
	0x5e, 0x69, 0x77, 0x68, 0xef, 0x38, 0x21, 0x93, 0x11, 0x4d, 0x7c, 0x0b, 0xe5, 0x04, 0xe5, 0x8d,
	0xc1, 0x84, 0xbd, 0x3a, 0x59, 0x6a, 0xee, 0x50, 0xde, 0x88, 0x8b, 0x31, 0x90, 0x38, 0x09, 0x71,
	0xf1, 0x3d, 0x0d, 0xcd, 0xfb, 0x40, 0x6d, 0xe6, 0x00, 0xe7, 0x1f, 0x51, 0x01, 0x5c, 0xcf, 0x49,
	0xaa, 0x0f, 0x26, 0xc8, 0x03, 0x32, 0x0c, 0x64, 0xbe, 0xa0, 0x08, 0xe7, 0x47, 0x96, 0x39, 0x49,
	0xf0, 0x61, 0x8a, 0x0a, 0x6d, 0xf5, 0x1a, 0x51, 0xd5, 0x3e, 0xf1, 0x63, 0x46, 0x3e, 0x32, 0x07,
	0x12, 0x89, 0x60, 0xf1, 0x2e, 0xca, 0x33, 0xc7, 0x6b, 0x0b, 0xae, 0x9f, 0x93, 0xce, 0x2d, 0x8f,
	0xed, 0xa1, 0xea, 0x11, 0x62, 0x10, 0x7a, 0x67, 0xf3, 0xae, 0x00, 0x47, 0x8e, 0xcb, 0xa8, 0x7b,
	0x6f, 0x49, 0x10, 0xa2, 0xc0, 0xaa, 0x0f, 0xb2, 0xe8, 0xf9, 0x13, 0xbf, 0x21, 0xfe, 0x6f, 0x15,
	0x86, 0xdf, 0x42, 0x73, 0x5e, 0x7b, 0xaf, 0xc9, 0xf8, 0x01, 0xd8, 0x66, 0x57, 0x25, 0xf8, 0xa2,
	0x82, 0x98, 0xdb, 0x8e, 0xb7, 0xc8, 0xf0, 0x39, 0xdc, 0x40, 0x0b, 0x4a, 0xdc, 0x61, 0x2d, 0xe0,
	0x82, 0xb6, 0x3c, 0x35, 0x26, 0x5f, 0x3f, 0xdd, 0x14, 0x0a, 0xd4, 0x4e, 0xe0, 0x59, 0x17, 0x24,
	0x05, 0x8c, 0xbf, 0x4f, 0x7f, 0x09, 0x04, 0x4c, 0x9f, 0x4d, 0xf7, 0x4b, 0x80, 0x01, 0x7f, 0xec,
	0xb7, 0xc0, 0x2a, 0x9a, 0x0d, 0x8a, 0x04, 0xbf, 0x31, 0xf2, 0xea, 0xd7, 0x13, 0xaf, 0xfe, 0x42,
	0x70, 0x26, 0x7e, 0xe0, 0x9b, 0x37, 0x0f, 0x8f, 0xca, 0x33, 0xf7, 0x8f, 0xca, 0x33, 0x0f, 0x8f,
	0xca, 0x33, 0xf7, 0xfa, 0x65, 0xed, 0xb0, 0x5f, 0xd6, 0xee, 0xf7, 0xcb, 0xda, 0xc3, 0x7e, 0x59,
	0xfb, 0xab, 0x5f, 0xd6, 0x7e, 0xfa, 0xbb, 0x3c, 0x73, 0x73, 0x75, 0x92, 0x7f, 0x63, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0x98, 0xd9, 0x47, 0xab, 0xc4, 0x11, 0x00, 0x00,
}

func (m *PackageRevision) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevision) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevision) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionApproval) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionApproval) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionApproval) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *PackageRevisionDependencies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionDependencies) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionDependencies) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dependencies) > 0 {
		for iNdEx := len(m.Dependencies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Dependencies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Warnings) > 0 {
		for iNdEx := len(m.Warnings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Warnings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Errors) > 0 {
		for iNdEx := len(m.Errors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Errors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Error != nil {
		i -= len(*m.Error)
		copy(dAtA[i:], *m.Error)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.Error)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PackageRevisionDependency) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionDependency) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionDependency) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RuntimeDependencies) > 0 {
		for iNdEx := len(m.RuntimeDependencies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RuntimeDependencies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PackageDependencies) > 0 {
		for iNdEx := len(m.PackageDependencies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PackageDependencies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Ref != nil {
		{
			size, err := m.Ref.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionDependencyError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionDependencyError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionDependencyError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Reason)
	copy(dAtA[i:], m.Reason)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Reason)))
	i--
	dAtA[i] = 0x12
	if m.Ref != nil {
		{
			size, err := m.Ref.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PackageRevisionList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionResources) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionResources) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionResources) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionResourcesList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionResourcesList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionResourcesList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionResourcesSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionResourcesSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionResourcesSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PackageID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Resources) > 0 {
		keysForResources := make([]string, 0, len(m.Resources))
		for k := range m.Resources {
			keysForResources = append(keysForResources, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForResources)
		for iNdEx := len(keysForResources) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Resources[string(keysForResources[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForResources[iNdEx])
			copy(dAtA[i:], keysForResources[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForResources[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PackageRevisionResourcesStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionResourcesStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionResourcesStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ConditionedStatus.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inputs) > 0 {
		for iNdEx := len(m.Inputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Inputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Upstream != nil {
		{
			size, err := m.Upstream.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.ReadinessGates) > 0 {
		for iNdEx := len(m.ReadinessGates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReadinessGates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Tasks) > 0 {
		for iNdEx := len(m.Tasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	i -= len(m.UpdatePolicy)
	copy(dAtA[i:], m.UpdatePolicy)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.UpdatePolicy)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Lifecycle)
	copy(dAtA[i:], m.Lifecycle)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Lifecycle)))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.PackageID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PackageRevisionStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackageRevisionStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackageRevisionStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Dependencies != nil {
		{
			size, err := m.Dependencies.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.PublishedAt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	i -= len(m.PublishedBy)
	copy(dAtA[i:], m.PublishedBy)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.PublishedBy)))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ConditionedStatus.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Task) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PackageRevision) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageRevisionApproval) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *PackageRevisionDependencies) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		l = len(*m.Error)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.Errors) > 0 {
		for _, e := range m.Errors {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.Warnings) > 0 {
		for _, e := range m.Warnings {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.Dependencies) > 0 {
		for _, e := range m.Dependencies {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageRevisionDependency) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	if m.Ref != nil {
		l = m.Ref.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.PackageDependencies) > 0 {
		for _, e := range m.PackageDependencies {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.RuntimeDependencies) > 0 {
		for _, e := range m.RuntimeDependencies {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageRevisionDependencyError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ref != nil {
		l = m.Ref.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.Reason)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageRevisionList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageRevisionResources) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageRevisionResourcesList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageRevisionResourcesSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Resources) > 0 {
		for k, v := range m.Resources {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	l = m.PackageID.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageRevisionResourcesStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ConditionedStatus.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PackageRevisionSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PackageID.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Lifecycle)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.UpdatePolicy)
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Tasks) > 0 {
		for _, e := range m.Tasks {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.ReadinessGates) > 0 {
		for _, e := range m.ReadinessGates {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.Upstream != nil {
		l = m.Upstream.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if len(m.Inputs) > 0 {
		for _, e := range m.Inputs {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PackageRevisionStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ConditionedStatus.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.PublishedBy)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.PublishedAt.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.Dependencies != nil {
		l = m.Dependencies.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PackageRevision) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevision{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PackageRevisionSpec", "PackageRevisionSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "PackageRevisionStatus", "PackageRevisionStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionApproval) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevisionApproval{`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionDependencies) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForErrors := "[]*PackageRevisionDependencyError{"
	for _, f := range this.Errors {
		repeatedStringForErrors += strings.Replace(f.String(), "PackageRevisionDependencyError", "PackageRevisionDependencyError", 1) + ","
	}
	repeatedStringForErrors += "}"
	repeatedStringForWarnings := "[]*PackageRevisionDependencyError{"
	for _, f := range this.Warnings {
		repeatedStringForWarnings += strings.Replace(f.String(), "PackageRevisionDependencyError", "PackageRevisionDependencyError", 1) + ","
	}
	repeatedStringForWarnings += "}"
	repeatedStringForDependencies := "[]*PackageRevisionDependency{"
	for _, f := range this.Dependencies {
		repeatedStringForDependencies += strings.Replace(f.String(), "PackageRevisionDependency", "PackageRevisionDependency", 1) + ","
	}
	repeatedStringForDependencies += "}"
	s := strings.Join([]string{`&PackageRevisionDependencies{`,
		`Error:` + valueToStringGenerated(this.Error) + `,`,
		`Errors:` + repeatedStringForErrors + `,`,
		`Warnings:` + repeatedStringForWarnings + `,`,
		`Dependencies:` + repeatedStringForDependencies + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionDependency) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPackageDependencies := "[]*Upstream{"
	for _, f := range this.PackageDependencies {
		repeatedStringForPackageDependencies += strings.Replace(fmt.Sprintf("%v", f), "Upstream", "pkgid.Upstream", 1) + ","
	}
	repeatedStringForPackageDependencies += "}"
	repeatedStringForRuntimeDependencies := "[]*ObjectReference{"
	for _, f := range this.RuntimeDependencies {
		repeatedStringForRuntimeDependencies += strings.Replace(fmt.Sprintf("%v", f), "ObjectReference", "v11.ObjectReference", 1) + ","
	}
	repeatedStringForRuntimeDependencies += "}"
	s := strings.Join([]string{`&PackageRevisionDependency{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Ref:` + strings.Replace(fmt.Sprintf("%v", this.Ref), "ObjectReference", "v11.ObjectReference", 1) + `,`,
		`PackageDependencies:` + repeatedStringForPackageDependencies + `,`,
		`RuntimeDependencies:` + repeatedStringForRuntimeDependencies + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionDependencyError) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevisionDependencyError{`,
		`Ref:` + strings.Replace(fmt.Sprintf("%v", this.Ref), "ObjectReference", "v11.ObjectReference", 1) + `,`,
		`Reason:` + fmt.Sprintf("%v", this.Reason) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]PackageRevision{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "PackageRevision", "PackageRevision", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PackageRevisionList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionResources) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevisionResources{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PackageRevisionResourcesSpec", "PackageRevisionResourcesSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "PackageRevisionResourcesStatus", "PackageRevisionResourcesStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionResourcesList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]PackageRevisionResources{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "PackageRevisionResources", "PackageRevisionResources", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&PackageRevisionResourcesList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionResourcesSpec) String() string {
	if this == nil {
		return "nil"
	}
	keysForResources := make([]string, 0, len(this.Resources))
	for k := range this.Resources {
		keysForResources = append(keysForResources, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForResources)
	mapStringForResources := "map[string]string{"
	for _, k := range keysForResources {
		mapStringForResources += fmt.Sprintf("%v: %v,", k, this.Resources[k])
	}
	mapStringForResources += "}"
	s := strings.Join([]string{`&PackageRevisionResourcesSpec{`,
		`Resources:` + mapStringForResources + `,`,
		`PackageID:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PackageID), "PackageID", "pkgid.PackageID", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionResourcesStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevisionResourcesStatus{`,
		`ConditionedStatus:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ConditionedStatus), "ConditionedStatus", "condition.ConditionedStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionSpec) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTasks := "[]Task{"
	for _, f := range this.Tasks {
		repeatedStringForTasks += strings.Replace(strings.Replace(f.String(), "Task", "Task", 1), `&`, ``, 1) + ","
	}
	repeatedStringForTasks += "}"
	repeatedStringForReadinessGates := "[]ReadinessGate{"
	for _, f := range this.ReadinessGates {
		repeatedStringForReadinessGates += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForReadinessGates += "}"
	repeatedStringForInputs := "[]RawExtension{"
	for _, f := range this.Inputs {
		repeatedStringForInputs += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForInputs += "}"
	s := strings.Join([]string{`&PackageRevisionSpec{`,
		`PackageID:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PackageID), "PackageID", "pkgid.PackageID", 1), `&`, ``, 1) + `,`,
		`Lifecycle:` + fmt.Sprintf("%v", this.Lifecycle) + `,`,
		`UpdatePolicy:` + fmt.Sprintf("%v", this.UpdatePolicy) + `,`,
		`Tasks:` + repeatedStringForTasks + `,`,
		`ReadinessGates:` + repeatedStringForReadinessGates + `,`,
		`Upstream:` + strings.Replace(fmt.Sprintf("%v", this.Upstream), "Upstream", "pkgid.Upstream", 1) + `,`,
		`Inputs:` + repeatedStringForInputs + `,`,
		`}`,
	}, "")
	return s
}
func (this *PackageRevisionStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PackageRevisionStatus{`,
		`ConditionedStatus:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ConditionedStatus), "ConditionedStatus", "condition.ConditionedStatus", 1), `&`, ``, 1) + `,`,
		`PublishedBy:` + fmt.Sprintf("%v", this.PublishedBy) + `,`,
		`PublishedAt:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PublishedAt), "Time", "v1.Time", 1), `&`, ``, 1) + `,`,
		`Dependencies:` + strings.Replace(this.Dependencies.String(), "PackageRevisionDependencies", "PackageRevisionDependencies", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Task) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Task{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PackageRevision) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevision: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevision: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionApproval) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionApproval: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionApproval: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionDependencies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionDependencies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionDependencies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Error = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Errors = append(m.Errors, &PackageRevisionDependencyError{})
			if err := m.Errors[len(m.Errors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warnings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Warnings = append(m.Warnings, &PackageRevisionDependencyError{})
			if err := m.Warnings[len(m.Warnings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dependencies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dependencies = append(m.Dependencies, &PackageRevisionDependency{})
			if err := m.Dependencies[len(m.Dependencies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionDependency) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionDependency: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionDependency: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = PackageRevisionDependencyType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ref", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ref == nil {
				m.Ref = &v11.ObjectReference{}
			}
			if err := m.Ref.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageDependencies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PackageDependencies = append(m.PackageDependencies, &pkgid.Upstream{})
			if err := m.PackageDependencies[len(m.PackageDependencies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeDependencies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuntimeDependencies = append(m.RuntimeDependencies, &v11.ObjectReference{})
			if err := m.RuntimeDependencies[len(m.RuntimeDependencies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionDependencyError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionDependencyError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionDependencyError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ref", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ref == nil {
				m.Ref = &v11.ObjectReference{}
			}
			if err := m.Ref.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PackageRevision{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionResources) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionResources: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionResources: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionResourcesList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionResourcesList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionResourcesList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PackageRevisionResources{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionResourcesSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionResourcesSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionResourcesSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Resources == nil {
				m.Resources = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Resources[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PackageID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionResourcesStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionResourcesStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionResourcesStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConditionedStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConditionedStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PackageID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PackageID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lifecycle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lifecycle = PackageRevisionLifecycle(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatePolicy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatePolicy = UpdatePolicy(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tasks = append(m.Tasks, Task{})
			if err := m.Tasks[len(m.Tasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReadinessGates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReadinessGates = append(m.ReadinessGates, condition.ReadinessGate{})
			if err := m.ReadinessGates[len(m.ReadinessGates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upstream", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Upstream == nil {
				m.Upstream = &pkgid.Upstream{}
			}
			if err := m.Upstream.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, runtime.RawExtension{})
			if err := m.Inputs[len(m.Inputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackageRevisionStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackageRevisionStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackageRevisionStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConditionedStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConditionedStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublishedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PublishedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dependencies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dependencies == nil {
				m.Dependencies = &PackageRevisionDependencies{}
			}
			if err := m.Dependencies.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Task) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Task: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Task: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = TaskType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
