apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.pkg.pkgserver.dev
spec:
  insecureSkipTLSVerify: true
  group: pkg.pkgserver.dev
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: pkg-server
    namespace: pkg-system
    port: 6444
  version: v1alpha1
