kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pkg-server-role
  namespace: pkg-system
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]