apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pkg-server-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pkg-server-clusterrole
subjects:
- kind: ServiceAccount
  name: pkg-server
  namespace: pkg-system
